### ISSUE TITLE
Beating on broker constantly

### ISSUE THREAD

**Issue by emanuelvianna** [emanuelvianna/microcelery#2]
@viniciuscainelli,

The inner while True keep beating on redis in bursts. We may fill redis buffer with unnecessary requests. Recall that redis is serial. It is probably better to keep only the outer while True. 

``` python
    def _listen_queue(self):
        while True:
            raw_task = self.rds.lpop(settings.QUEUE_KEY)
            if raw_task:
                self._execute_task(raw_task)
            else:
                break

    def run(self):
        while True:
            self._listen_queue()
            time.sleep(0.5)
```

What do you think?

VBR,
Emanuel

**Comment by viniciuscainelli** [comment]
Something like that?

``` python
    def _listen_queue(self):
        while True:
            raw_task = self.rds.lpop(settings.QUEUE_KEY)
            if raw_task:
                self._execute_task(raw_task)
            else:
                break

            time.sleep(0.5)

    def run(self):
        self._listen_queue()
```

What do you think?

**Comment by viniciuscainelli** [comment]
But did you see the `sleep`?
I think that the number of times that are beating on broker didn't change.
The inner while True is used only to navigate each item in the `list`, on Redis. (note the `break`).

**Comment by emanuelvianna** [comment]
I think that put the loop in `run` is more consonant with our func names. Every loop iteration we try to `listen` the queue. Makes more sense for me.

``` python
    def _listen_queue(self):
        raw_task = self.rds.lpop(settings.QUEUE_KEY)
        if raw_task:
            self._execute_task(raw_task)
        else:
            break

    def run(self):
        while True:
            self._listen_queue()
            time.sleep(0.5)
```

**Comment by emanuelvianna** [comment]
yeap! we'll not troll redis that way

**Comment by viniciuscainelli** [comment]
thinking about that... note that if one task is executing, the second task will start after 0.5 seconds. this is not good.

**Comment by emanuelvianna** [comment]
good point! 

<img src="http://static.carthrottle.com/workspace/uploads/comments/good-job-53f2066b858f7.jpg" width="200px"/>

**Comment by viniciuscainelli** [comment]
![](https://s-media-cache-ak0.pinimg.com/originals/cd/42/6e/cd426e36592d08c2abced87092b4c3a0.gif)

**Comment by emanuelvianna** [comment]
the way it is now the outer loop will never be executed, we have two options:
1-remove outer loop
2-replace while True in inner loop by a while not empty

**Comment by viniciuscainelli** [comment]
``` python
    def _listen_queue(self):
        raw_task = self.rds.lpop(settings.QUEUE_KEY)
        while raw_task:
            self._execute_task(raw_task)
            raw_task = self.rds.lpop(settings.QUEUE_KEY)

    def run(self):
        while True:
            self._listen_queue()
            time.sleep(0.5)
```

and now?

**Comment by emanuelvianna** [comment]
perfect!

<img src="http://memecrunch.com/meme/3S1DQ/lgtm/image.jpg" width="200px"/>
